#!/usr/bin/env bash
#print different message, delete and terminate itself upon execution of a SIGINT /SIGTERM
echo "$$" > /var/run/myscript.pid
trap "echo 'I hate the kill command'; rm -rf /var/run/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -rf /var/run/myscript.pid; exit" SIGINT
while true
do
    echo "To infinity and beyond"
    sleep 2
done

